defaults: 
 - data: stl10
 - model: resnet_simclr
 - experiment: self_supervised
 - _self_

seed: 42
device: "cuda"
epochs: 1
learning_rate: 0.03
batch_size: 32


logger:
  project: "contrastive_learning"
  group: ${experiment.mode}