defaults: 
 - data: stl10
 - model: resnet_simclr
 - experiment: self_supervised
 - _self_

seed: 42
device: "cuda"
epochs: 150
<<<<<<< HEAD
batch_size: 32
num_workers: 6
=======
batch_size: 16
num_workers: 4
>>>>>>> 8fe8cf4a58355c632a5751368c1c4fb042f95266
stage: all

checkpoint_path: null  
auto_last_checkpoint: True

model_config:
  out_dim: 128     
  hidden_dim: 512  

logger:
  project: "contrastive_learning"
  group: ${experiment.mode}