defaults: 
 - data: stl10
 - model: resnet_simclr
 - _self_

seed: 42
device: "cuda"
epochs: 1
learning_rate: 0.0003
batch_size: 32

experiment:
  mode: "self_supervised"
  supervised: false
  temperature: 0.07

logger:
  project: "contrastive_learning"
  group: ${experiment.mode}