defaults:
  - data: cic_2018_v2            
  - model: netflow_contrastive   
  - loss: contrastive            
  - optimizer: adamw             
  - scheduler: cosine_warmup
  - experiment: self_supervised
  - path: default 
  - _self_

seed: 42
name: selfsup_cic2018
device: cuda
run_id: 0
stage: all

logger:
  wandb:
    project: contrastive_learning
    entity: Carmine 
    offline: false
    id: ${run_id}

hydra:
  run:
    dir: .
  job:
    chdir: False
